### PR TITLE
Bugfixes

### LINKED ISSUE #156: Markdown tables still break the UI sometimes.
If you ask this question : 

Image

And then ask for a table, it will sometimes make it horizontal and very big : 

Image

This is due to that : https://github.com/openbraininstitute/neuroagent/blob/73239b71224547a54296ca223f920903e5020301/frontend/src/components/chat/chat-message-ai.tsx#L47 
Changing this to a `<div>` fixes it. Then some more tweaking to the rest of the UI needs to be done.

### LINKED ISSUE #157: Shift + Enter should add new lines to the input
In #149 we made sure `Shift + Enter` does not submit.

However, I suggest we try to copy ChatGPT (see the screenrecording) and make sure that it not only does not submit but also it adds a new line to the input.

Note that the behavior should be the same in the `/` and in `/threads/{threadId}`

https://github.com/user-attachments/assets/ad6f026a-e642-44f6-a301-22b7858d0e20

### LINKED ISSUE #164: Use structured output to generate the title
So I used a different LLM (llama3.2) and the title generation endpoint contained the suggested title but also some AI comments

> It seems like you're starting our conversation! Here's a possible short title:"Hello from AI Companion"

I suggest we use structured output to guarantee we only get what we need

https://platform.openai.com/docs/guides/structured-outputs

https://github.com/openbraininstitute/neuroagent/blob/a05a263a5b9c8b1316c66104d60322a98eda629b/backend/src/neuroagent/app/routers/threads.py#L86-L96

### LINKED ISSUE #179: Error message in production are not shown properly.
Image

In `app/threads/[threadId]/error.tsx` i have made it so that it displays the error message. It works in `dev` but not in docker compose. 
We can add a generic error message and then add `notFound.tsx` for 404 errors (https://nextjs.org/learn/dashboard-app/error-handling).

### LINKED ISSUE #191: Editing title of recent thread proposes wrong text
https://github.com/user-attachments/assets/3ca906b6-ef27-4eae-a673-f82e92de4f82

The `New Chat` should not be there.

As soon as one refreshes (and refetches the sidebar) it shows the correct title

### LINKED ISSUE #194: Specify species in the hardcoded default questions
https://github.com/openbraininstitute/neuroagent/blob/0c7493a8af2c02d89bc21523f2b2e184bd526339/frontend/src/components/chat/question-suggestion-cards.tsx#L10-L24

We should just add "of rodents" at the end of all of those. Note that there will probably be an independent ticket for adding the species to the user journey (if not you can directly do it here)

### PR DESCRIPTION
**Pull request by BoBer78**
closes #194  closes #156 closes #157 closes #179  closes #191  closes #164

### CODE REVIEW

File: frontend/src/lib/fetcher.ts [hunk 1]
```diff
@@ -64,6 +65,9 @@ export async function fetcher({
   });
 
   if (!response.ok) {
+    if (response.status === 404) {
+      return notFound();
```
Comment (jankrepl) [inline frontend/src/lib/fetcher.ts:69]: I don't like the idea of calling the `notFound()` here. 

Looking at the official docs https://nextjs.org/docs/app/api-reference/functions/not-found they clearly put this inside the `page.tsx` - or in other words it is done on the "Page" level. This `fetcher.ts` was designed to implement data fetching logic completely independently of react/nextjs. One example of that is that  `frontend/src/hooks/fetch.ts` wraps the fetcher inside react query. And there raising the exception is key to get correct status information and retries.

Alternative (chatgpt assisted)

Define a new subclass of `Error` and then include the statusCode inside and then you can always try/catch when you call it

```javascript
class CustomError extends Error {
    constructor(message, statusCode) {
        super(message); // Call the parent constructor
        this.statusCode = statusCode; // Add custom property
        this.name = this.constructor.name; // Set error name dynamically
        Error.captureStackTrace(this, this.constructor); // Preserve stack trace
    }
}

// Example usage:
try {
    throw new CustomError("Not Found", 404);
} catch (error) {
    console.log(error.message);     // "Not Found"
    console.log(error.statusCode);  // 404
    console.log(error.stack);       // Full stack trace
}

```

Comment (BoBer78) [reply frontend/src/lib/fetcher.ts:69]: I personally hate the fact that the fetcher implements the error handling. I tried before to make this custom error class and NextJS transforms it back to a normal error and I lost all the additional parameters.
I'll try to put the `NotFound` in page.tsx, and not the fetcher.

Comment (jankrepl) [reply frontend/src/lib/fetcher.ts:69]: Point taken @BoBer78 

Alternative 2) return the error and have two return types (one for success and the other one for error)

Alternative 3) don't use this fetcher at all..just write a raw `fetch` whenever you data. Not pointing figures but @WonderPG pushed for this approach of having some "fetching" wrapper that every component is forced to use but IMO it assumes that your wrapper fits every single use case which imo is hard

Comment (BoBer78) [reply frontend/src/lib/fetcher.ts:69]: I'll try your solution 1), and then if it is not to complicated we can go with it !

File: backend/tests/mock_client.py [hunk 2]
```diff
@@ -27,42 +38,82 @@ def create_mock_response(message, function_calls=[], model="gpt-4o-mini"):
...
+                        refusal=None,
+                        role=role,
+                        audio=None,
+                        function_call=None,
+                        tool_calls=tool_calls,
+                        parsed=structured_output_class,
+                    ),
+                )
+            ],
+        )
```
[the remark this answers is not in the document]
Comment (BoBer78) [reply backend/tests/mock_client.py:79]: I like the idea, I'll try to implement it like that !

[the remark this answers is not in the document]
Comment (BoBer78) [reply backend/tests/mock_client.py]: Done in [981aebb](https://github.com/openbraininstitute/neuroagent/pull/195/commits/981aebbd29dfbe4f572afc789c271b0dca31f827).

File: frontend/src/lib/fetcher.ts (hunk 1 above)
Comment (BoBer78) [reply frontend/src/lib/fetcher.ts]: Done in [dbbabb1](https://github.com/openbraininstitute/neuroagent/pull/195/commits/dbbabb11ddbff01669a9e1a3098e4c48c60dec9e). I used solution 1 and I put notFond in the pages.

**Comment by jankrepl** [comment]
Regarding the multiline it is almost perfect - can you please just make sure there is enough padding? The text should not "touch" the border


https://github.com/user-attachments/assets/b5be13f2-165a-416a-8764-85127f516d40

File: frontend/src/app/tools/[toolName]/not-found.tsx [hunk 3]
```diff
@@ -0,0 +1,37 @@
...
+  reset,
+}: {
+  error: Error & { digest?: string };
+  reset: () => void;
+}) {
+  useEffect(() => {
+    // Log the error to an error reporting service
+    console.error(error);
+  }, [error]);
+
```
Comment (jankrepl) [inline frontend/src/app/tools/[toolName]/not-found.tsx:18]: So we need to keep this one in here? I would remove it everywhere.


https://github.com/user-attachments/assets/b451be3e-1329-4431-8650-76309ce47e86

**Comment by jankrepl** [comment]
Amazing job:) I tried it locally and left some minor comments above. I will approve once you address them

@BoBer78

**Comment by jankrepl** [comment]
One thing that surprised me was that we do allow for multiline input but then somehow the new lines are lost inside the `chat-message-human`...is that on purpose?

ChatGPT does preserve them


https://github.com/user-attachments/assets/9a4d61ad-8cfa-4b38-af6e-d26e06b359b0

**Comment by BoBer78** [comment]
> One thing that surprised me was that we do allow for multiline input but then somehow the new lines are lost inside the `chat-message-human`...is that on purpose?
> 
> ChatGPT does preserve them
> Screen.Recording.2025-03-12.at.12.35.07.mov

My guess is that we should also support some kind of formating in the Humain message box. Maybe even markdown

**Comment by jankrepl** [comment]
> > One thing that surprised me was that we do allow for multiline input but then somehow the new lines are lost inside the `chat-message-human`...is that on purpose?
> > ChatGPT does preserve them
> > Screen.Recording.2025-03-12.at.12.35.07.mov
> 
> My guess is that we should also support some kind of formating in the Humain message box. Maybe even markdown

I don't think ChatGPT supports markdown for human messages. Might be an overkill. But I would definitely support new line.

**Comment by BoBer78** [comment]
> > > One thing that surprised me was that we do allow for multiline input but then somehow the new lines are lost inside the `chat-message-human`...is that on purpose?
> > > ChatGPT does preserve them
> > > Screen.Recording.2025-03-12.at.12.35.07.mov
> > 
> > 
> > My guess is that we should also support some kind of formating in the Humain message box. Maybe even markdown
> 
> I don't think ChatGPT supports markdown for human messages (at least I did not manage to trigger it). Might be an overkill. But I would definitely support new line.

I added line breaks in the human message, it was a simple Tailwind class

File: frontend/src/app/threads/[threadId]/not-found.tsx [hunk 4]
```diff
@@ -0,0 +1,23 @@
+"use client";
+
+import { Button } from "@/components/ui/button";
+import Link from "next/link";
+
+export default function NotFound() {
+  return (
+    <div className="container mx-auto px-4 py-6 h-[calc(100vh-4rem)] flex flex-col items-center justify-center">
+      <div className="text-center space-y-4">
+        <h2 className="text-2xl font-bold">404 not found.</h2>
```
Comment (jankrepl) [inline frontend/src/app/threads/[threadId]/not-found.tsx:10]: Detail.

I would just unify this with `tools/[toolName]/not-found.tsx`


There we say `404 Not Found` (here we say `404 not found.`)

File: frontend/src/app/tools/[toolName]/not-found.tsx [hunk 5]
```diff
@@ -0,0 +1,25 @@
...
+        <p className="text-muted-foreground">
+          The requested tool could not be found.
+        </p>
+        <div className="flex gap-4 justify-center mt-6">
+          <Link href="/tools">
+            <Button>Return to Tools</Button>
+          </Link>
+          <Button variant="outline" onClick={() => reset()}>
+            Try again
+          </Button>
```
[the remark this answers is not in the document]
Comment (BoBer78) [reply frontend/src/app/tools/[toolName]/not-found.tsx:20]: Should I also remove it in the `error.tsx` page ?

**Review by jankrepl — APPROVED** [review]
